env:
  es2021: true
  node: true
  browser: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parser: babel-eslint

parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - req
      - reply
